### ISSUE TITLE
preprocessing missing?

### ISSUE THREAD

**Issue by csgroen** [KnottLab/bladder-snSeq#2]
Hi,

When trying to reproduce the first figure, even after installing the requirements in the `pip_freeze.txt`, I run into the following error:

```
GSE169379_MIBC_snSeq.h5ad.clust.h5ad
[DO_UMAP] WARNING failed to import cuML. GPU accelerated UMAP will not be available.
[DO_TSNE] WARNING failed to import cuML. GPU accelerated TSNE will not be available.
Traceback (most recent call last):
  File "./scvi_.py", line 17, in <module>
    from preprocessing import run_preprocess, add_preprocess_args
ModuleNotFoundError: No module named 'preprocessing'
Traceback (most recent call last):
  File "./do_umap.py", line 84, in <module>
    adata = load_data(ARGS.dataset)
  File "/content/drive/MyDrive/SingleCell/Gouin/bladder-snSeq/Figure_1/initial_subtyping/load_data.py", line 44, in load_data
    assert os.path.exists(pth), f'WARNING: {pth}'
AssertionError: WARNING: GSE169379_MIBC_snSeq.h5ad.clust.h5ad
Traceback (most recent call last):
  File "./do_tsne.py", line 88, in <module>
    adata = load_data(ARGS.dataset)
  File "/content/drive/MyDrive/SingleCell/Gouin/bladder-snSeq/Figure_1/initial_subtyping/load_data.py", line 44, in load_data
    assert os.path.exists(pth), f'WARNING: {pth}'
AssertionError: WARNING: GSE169379_MIBC_snSeq.h5ad.clust.h5ad
Traceback (most recent call last):
  File "./cluster_.py", line 159, in <module>
    adata = load_data(ARGS.dataset)
  File "/content/drive/MyDrive/SingleCell/Gouin/bladder-snSeq/Figure_1/initial_subtyping/load_data.py", line 44, in load_data
    assert os.path.exists(pth), f'WARNING: {pth}'
AssertionError: WARNING: GSE169379_MIBC_snSeq.h5ad.clust.h5ad
```

There is a pip package called preprocessing, I installed it to try, but I believe `preprocessing` is some sort of in-house library?
I downloaded the h5ad from GSE (for both MIBC and non-tumor), and ran into the error using the tumor h5ad GSE.

Any advice would be appreciated.

**Comment by nathanin** [comment]
Hi, thank you so much for letting me know about this omission. You're absolutely right `preprocessing.py` is an internal module that I've just added to this repository here: https://github.com/KnottLab/bladder-snSeq/blob/master/Figure_1/initial_subtyping/preprocessing.py  

Practically, since the first thing we do in `run_scvi` is reset the data to the `adata.raw` counts values, this module doesn't do much for us other than apply Mito genes filtering and highly variable gene selection.

Please let me know if you come across any other issues
